plugins:
  - jekyll-scholar
#  - jekyll-mermaid

mermaid:
  # src: 'https://unpkg.com/mermaid@11.4.1/dist/mermaid.min.js'
  # src_config: '/js/mermaid_config.js'
  version: "11.4.1"


title: SQRBOK - Handbook
author: Andrey Sadovykh
description: "Software Quality and Reliability Course Handbook (SQRBOK) - Collection of resources and handouts"
theme: just-the-docs

url: https://msdbok.github.io/justdocs/

aux_links:
  Handbook Repo: https://github.com/msdbok/justdocs
