# documentation: https://just-the-docs.github.io/just-the-docs/docs/configuration/
# source: https://github.com/just-the-docs/just-the-docs/blob/main/_config.yml

plugins:
  - jekyll-scholar
#  - jekyll-mathjax
#  - jekyll-mermaid

scholar:
  style: ieee

mermaid:
  # src: 'https://unpkg.com/mermaid@11.4.1/dist/mermaid.min.js'
  # src_config: '/js/mermaid_config.js'
  version: "11.4.1"

math: mathjax


title: MSDBOK - Handbook
author: Andrey Sadovykh
description: "Managing Software Development Course Handbook (MSDBOK) - Collection of resources and handouts"
theme: just-the-docs

url: https://msdbok.github.io

logo: "/images/msdbok_logo.png"

favicon_ico: "/images/favicon.ico"

aux_links:
  Handbook Repo: https://github.com/msdbok/msdbok.github.io

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


